variables:
  VERSION: $CI_COMMIT_SHORT_SHA
  RELEASE: $CI_COMMIT_TAG
  DOCKER_DRIVER: overlay2

  CI_DEBUG_TRACE: "true"

  ## deployment relatet
  KUBERNETES_SHORTNAME: $p03_KUBERNETES_SHORTNAME
  KUBERNETES_URL: $p03_KUBERNETES_URL
  KUBERNETES_USER: $p03_KUBERNETES_USER
  KUBERNETES_USER_TOKEN: $p03_KUBERNETES_USER_TOKEN
  KUBERNETES_NAMESPACE: $PROJECT_NAMESPACE

  ## select jobs

default:
  tags:
    - private-arlindne

stages:
  - build
  - test
  - pages
  - publish
  - deploy
  - cleanup

# Built-in secret detection
# Code has been  derived from: https://gitlab.devops.telekom.de/ccoe/training/training-day-2021-04-08/session-3 and slightly adapted.
# To use this CI template, please include it in your pipeline and implement the "security scan" stage.
include:
  - local: /gitlab-safescarf.yml

pages:
  stage: publish
  image: 
    name: dockerhub.devops.telekom.de/alpine:3
    entrypoint: [""]
  tags:
    - otc_run_docker_s
  script:
    - mkdir public
    - cp index.html public/
    - cp -r implementations/ public/
    - cp gitlab-safescarf.yml public/
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
