---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.13.0
    hooks:
      - id: markdownlint
        args: [--config=.linter-config/mdlrc]
  - repo: https://github.com/thoughtworks/talisman
    rev: 'v1.31.0'  # Update me!
    hooks:
    # either `commit` or `push` support
    # -   id: talisman-push
      - id: talisman-commit
        entry: cmd --githook pre-commit
